version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6  # primary container for the build job
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Running tests
          command: |
            . run_all.sh
